name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write  # Allows pushing changes to the repository

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: "nicoware-dev"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: "github-contribution-grid-snake.svg"  # Specify the output file

      - name: List files in workspace
        run: ls -R

      - name: Commit snake game image
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-contribution-grid-snake.svg || exit 0
          git commit -m "Update GitHub Contribution Snake Game" || exit 0
          git push || exit 0
