name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  actions: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Updated to v3

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: "nicoware-dev"
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          INPUT_SVG_OUT_PATH: "dist/github-contribution-grid-snake.svg"
          INPUT_GIF_OUT_PATH: "dist/github-contribution-grid-snake.gif"

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist
